// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pjqeidqpehtuurxtegzo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBqcWVpZHFwZWh0dXVyeHRlZ3pvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1Njg1NzksImV4cCI6MjA2NzE0NDU3OX0.EXFHlXMucdPsDhLUq5wKuLFQ50sX_9d_OD3YBSWBAHU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});